proxy-groups:

  - name: 🚀 节点选择
    type: select
    proxies:
      - 自动选择
      - 故障转移
      - 🇭🇰 香港节点
      - 🇺🇸 美国节点
      - 🇯🇵 日本节点
      - 🇨🇳 台湾节点
      - 🇸🇬 新加坡节点
      - 🇰🇷 韩国节点
      - Bitz Net


  - name: 🇭🇰 香港节点
    type: url-test
    include-all: true
    filter: "香港"
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50


  - name: 🇺🇸 美国节点
    type: url-test
    include-all: true
    filter: "美国"
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 100


  - name: 🇯🇵 日本节点
    type: url-test
    include-all: true
    filter: "日本"
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50


  - name: 🇨🇳 台湾节点
    type: url-test
    include-all: true
    filter: "台湾"
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50


  - name: 🇸🇬 新加坡节点
    type: url-test
    include-all: true
    filter: "新加坡|狮城"
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50


  - name: 🇰🇷 韩国节点
    type: url-test
    include-all: true
    filter: "韩国"
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50


  - name: 💬 Ai平台
    type: select
    proxies:
      - 🚀 节点选择
      - 美国节点
      - 日本节点
      - 自动选择


  - name: 📲 电报消息
    type: select
    proxies:
      - 🚀 节点选择
      - 自动选择


  - name: 📹 油管视频
    type: select
    proxies:
      - 🚀 节点选择
      - 自动选择


  - name: 🎥 奈飞视频
    type: select
    proxies:
      - 🚀 节点选择
      - 香港节点
      - 美国节点


  - name: 🎮 游戏平台
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择
      - 美国节点
      - 香港节点


  - name: 🛑 广告拦截
    type: select
    proxies:
      - REJECT
      - DIRECT


  - name: 🍃 应用净化
    type: select
    proxies:
      - REJECT
      - DIRECT


  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT


  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - 🚀 节点选择
      - 自动选择
      - DIRECT



rule-providers:

  LocalAreaNetwork:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
    path: ./ruleset/LocalAreaNetwork.list
    interval: 86400


  BanAD:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
    path: ./ruleset/BanAD.list
    interval: 86400


  BanProgramAD:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
    path: ./ruleset/BanProgramAD.list
    interval: 86400


  Steam:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
    path: ./ruleset/Steam.list
    interval: 86400


  YouTube:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
    path: ./ruleset/YouTube.list
    interval: 86400


  Netflix:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
    path: ./ruleset/Netflix.list
    interval: 86400


  Telegram:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
    path: ./ruleset/Telegram.list
    interval: 86400


  OpenAI:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
    path: ./ruleset/OpenAI.list
    interval: 86400



rules:

  - RULE-SET,LocalAreaNetwork,🎯 全球直连

  - RULE-SET,BanAD,🛑 广告拦截

  - RULE-SET,BanProgramAD,🍃 应用净化

  - RULE-SET,Steam,🎮 游戏平台

  - RULE-SET,YouTube,📹 油管视频

  - RULE-SET,Netflix,🎥 奈飞视频

  - RULE-SET,Telegram,📲 电报消息

  - RULE-SET,OpenAI,💬 Ai平台


  - GEOIP,CN,🎯 全球直连

  - MATCH,🐟 漏网之鱼
